env:
  cudagraph: true
  datasizes:
  - 512
  - 1024
  - 1536
  - 2048
  - 2560
  - 3072
  - 3584
  - 4096
  - 8192
  env_id: matmul
  episode_len: 1
  eval_dev: 3
  fp: 16
  repeat: 100
  search_space:
  - - 16
    - 32
    - 64
    - 128
    - 256
    - 512
  - - 16
    - 32
    - 64
    - 128
    - 256
    - 512
  - - 16
    - 32
    - 64
    - 128
    - 256
    - 512
  - - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
  - - 2
    - 4
    - 8
    - 16
    - 32
  sim: true
  size: 0
  train_dev: 7
  warmup: 0
general:
  log_wandb: true
  mode: train
  name: nrm_obs-eps1-sim_ms-allsize
  verbose: 0
train:
  algorithm: SAC
  eval_freq: 500
  framestack: null
  model_save_freq: 50000
  n_envs: 1
  n_eval_episodes: 1
  random_sample: true
  seed: 0
  total_timesteps: 300000
